language: python
sudo: false
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO=1.5
  - DJANGO=1.6.4
  - DJANGO=1.7.1
  - DJANGO=1.8.2
install:
  - pip install -q Django==$DJANGO
  - pip install -r requirements-test.txt
  - pip install -e .
script:
  - coverage run --source klingon setup.py test
after_success:
  - coveralls
